# Generated by Django 3.0.8 on 2022-03-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properies', '0002_auto_20220323_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_type',
            name='property_type',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
