# Generated by Django 3.0.8 on 2022-03-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properies', '0003_auto_20220323_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properies.property_type'),
        ),
    ]
