# Generated by Django 3.0.8 on 2022-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properies', '0006_auto_20220323_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
