# Generated by Django 3.0.8 on 2022-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properies', '0009_auto_20220425_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
