# Generated by Django 3.0.8 on 2022-05-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properies', '0014_auto_20220517_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_image',
            name='ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properies.property'),
        ),
    ]
