# Generated by Django 3.0.8 on 2022-06-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properies', '0016_auto_20220531_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency_type',
            options={'verbose_name_plural': 'Currency Type'},
        ),
        migrations.AlterModelOptions(
            name='price_freq',
            options={'verbose_name_plural': 'Sale Type'},
        ),
        migrations.AlterModelOptions(
            name='property_image',
            options={'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterModelOptions(
            name='property_status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='property_type',
            options={'verbose_name_plural': 'Property Types'},
        ),
        migrations.RenameField(
            model_name='property_image',
            old_name='ID',
            new_name='link_ID',
        ),
    ]
