# Generated by Django 3.0.8 on 2022-06-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properies', '0018_auto_20220614_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feature',
            new_name='features',
        ),
    ]
